---
title: "Analysis results"
author: "Akihiro Shiroshita"
date: "2022-10-20"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)


packages = c("devtools",
             "usethis",
             "here",
             "readr",
             "readxl",
             "expss",
             "tidyverse",
             "tidylog",
             "lubridate",
             "ggplot2",
             "ggplotgui",
             "ggthemes",
             "arsenal",
             "stats",
             "epitools",
             "DescTools",
             "epiR",
             "RVAideMemoire",
             "tableone",
             "flextable",
             "huxtable",
             "naniar",
             "VIM",
             "margins",
             "modmarg",
             "broom",
             "aod",
             "fitdistrplus",
             "rms",
             "Hmisc",
             "mice",
             "mitools",
             "margins")

package.check <- lapply(packages, FUN = function(x){
  if (!require(x, character.only = TRUE)){
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})
```

# Setting-up data for analysis  

```{r}
df <- read_csv(here("output/analysis_data.csv"))

df <- df %>% 
  mutate(enroll_age = trunc(time_length(interval(INFANTDOB, STUDYENROLLDATE), "month")),
         MAT_EDUC_cat = case_when(MAT_EDUCYEARS < 9 ~ 0,
                                  9 <= MAT_EDUCYEARS & MAT_EDUCYEARS <= 12 ~ 1,
                                  12 < MAT_EDUCYEARS ~ 2),
         other_sib_cat = case_when(OTHERLIVSIBS_BIO + OTHERLIVSIBS_HAL == 0 ~ 0,
                                   OTHERLIVSIBS_BIO + OTHERLIVSIBS_HAL == 1 ~ 1,
                                   1 < OTHERLIVSIBS_BIO + OTHERLIVSIBS_HAL ~ 2),
         rsv_pcr_age = trunc(time_length(interval(INFANTDOB, rftodaydate), "day")),
         rsv_sero_age = trunc(time_length(interval(INFANTDOB, lmday1), "day")))

```

# Patient chatacteristics  

```{r}
vars <- df %>% 
  dplyr::select(enroll_age, sex, ethnicity, MAT_EDUC_cat, MAT_MARITAL_STATUS, INSURANCE_CHILD, GESTAGEWK,
                MATSMOKE_PREG, BIRTHWEIGHT_GRAM, DELIVERYMODE, EVERBREASTFED, DAYCARE_OY, other_sib_cat,
                rsv_pcr_age, vy_rec_whz_dev) %>%
  colnames()
factorVars <- df %>% 
  dplyr::select(sex, ethnicity, MAT_EDUC_cat, MAT_MARITAL_STATUS, INSURANCE_CHILD, 
                MATSMOKE_PREG, DELIVERYMODE, EVERBREASTFED, DAYCARE_OY, other_sib_cat,
                vy_rec_whz_dev) %>%
  colnames()

table0 <- CreateTableOne(vars = vars,
                         data = df,
                         includeNA = FALSE,
                         factorVars = factorVars)
table0 %>% 
  print(test = FALSE, contDigits = 1, catDigits = 1) 
```
# Complete case analysis (categorized age)  

```{r}
df_comp <- df %>% 
  dplyr::select(vycurrentasthma_dev, rsv_pcr_age, rsv_sero_age, sex, ethnicity, DELIVERYMODE, MATSMOKE_PREG,
                MAT_ASTHMA_EVER, INSURANCE_CHILD, EVERBREASTFED, DAYCARE_OY) %>% 
  mutate(rsv_age_cat = case_when(rsv_pcr_age < 180 ~ 0,
                                 (180 < rsv_pcr_age & rsv_pcr_age < 365) ~ 1,
                                 (365 < rsv_pcr_age | (is.na(rsv_pcr_age) & is.na(rsv_sero_age))) ~ 2))

# crude
fit_comp_crude_cat <- glm(vycurrentasthma_dev ~ factor(rsv_age_cat),
                          family = binomial(link = "logit"),
                          data = df_comp)
tidy(fit_comp_crude_cat, exponentiate = TRUE, conf.int = TRUE)
# adjusted
fit_comp_adjusted_cat <- glm(vycurrentasthma_dev ~ factor(rsv_age_cat) + sex + ethnicity + DELIVERYMODE + 
                          MAT_ASTHMA_EVER + INSURANCE_CHILD + MATSMOKE_PREG +
                          EVERBREASTFED + DAYCARE_OY,
                          family = binomial(link = "logit"),
                          data = df_comp)
tidy(fit_comp_adjusted_cat, exponentiate = TRUE, conf.int = TRUE)
```

# Complete case analysis (continuous age)
```{r}
ddist <- datadist(df)
options(datadist='ddist')

# crude
fit_crude_rcs <- lrm(vycurrentasthma_dev ~ rcs(rsv_pcr_age, 5), data=df_comp)
summary(fit_crude_rcs)
ggplot(Predict(fit_crude_rcs, fun=exp, "rsv_pcr_age"), ylab="Odds ratio")

# adjusted
fit_adjusted_rcs <- lrm(vycurrentasthma_dev ~ rcs(rsv_pcr_age, 5) + sex + ethnicity + DELIVERYMODE + 
                          MAT_ASTHMA_EVER + INSURANCE_CHILD + MATSMOKE_PREG +
                          EVERBREASTFED + DAYCARE_OY, data=df_comp)
summary(fit_adjusted_rcs)
ggplot(Predict(fit_adjusted_rcs, fun=exp, "rsv_pcr_age"), ylab="Odds ratio")
```

# Imputation  

```{r}
df_imp <- df %>%
  filter(oy_rsv_infected_dev == 1) %>% 
  dplyr::select(vycurrentasthma_dev, rsv_pcr_age, sex, ethnicity,
                DELIVERYMODE, MATSMOKE_PREG, MAT_ASTHMA_EVER, INSURANCE_CHILD, EVERBREASTFED, DAYCARE_OY,
                MAT_MARITAL_STATUS, other_sib_cat, MAT_EDUC_cat # auxiliary variables
                ) %>% 
  mutate(vycurrentasthma_dev = as.logical(vycurrentasthma_dev),
         sex = as.logical(sex),
         ethnicity = as.factor(ethnicity),
         DELIVERYMODE = as.logical(DELIVERYMODE),
         MATSMOKE_PREG = as.logical(MATSMOKE_PREG),
         MAT_ASTHMA_EVER = as.logical(MAT_ASTHMA_EVER),
         INSURANCE_CHILD = as.factor(INSURANCE_CHILD),
         EVERBREASTFED = as.logical(EVERBREASTFED),
         DAYCARE_OY = as.logical(DAYCARE_OY),
         MAT_MARITAL_STATUS = as.factor(MAT_MARITAL_STATUS),
         other_sib_cat = as.factor(other_sib_cat),
         MAT_EDUC_cat = as.factor(MAT_EDUC_cat)) 

df_imp0 <- mice(df_imp, maxit = 0) 
df_imp0$method
df_imp0$predictorMatrix
predmt <- (1-diag(1, ncol(df_imp)))

m <- 100

df_imp100 <- mice(df_imp,
                  m = m,
                  maxit = 20,
                  predictorMatrix = predmt,
                  printFlag = FALSE,
                  seed = 1234)

plot(df_imp100)
```

# Outcome analysis  
```{r}
df_imp_stack <- complete(df_imp100, action = "long") %>% 
  as_tibble()

df_imp_stack_results <- df_imp_stack %>% 
  group_by(.imp) %>% 
  mutate(rsv_age_cat = case_when(rsv_pcr_age < 180 ~ 0,
                                 (180 <= rsv_pcr_age & rsv_pcr_age < 365) ~ 1)) %>% 
  nest() %>% 
  mutate(fit_imp = map(data, ~glm(vycurrentasthma_dev ~ factor(rsv_age_cat) + sex + ethnicity + DELIVERYMODE + 
                          MAT_ASTHMA_EVER + INSURANCE_CHILD + MATSMOKE_PREG +
                          EVERBREASTFED + DAYCARE_OY,
                          family = binomial(link = "logit"),
                          data = .)),
         ame = margins(fit_imp, variables = "rsv_age_cat")) 

df_imp_stack_results_combined <- MIcombine(df_imp_stack_results$fit_imp, call = NULL)
summary <- summary(df_imp_stack_results_combined)
exp(summary[, 1:4])
```

